spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/sahibinden_db
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: 3232

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL10Dialect


